from .ethnic import *
from .auth import *
from .role import *
from .user import *
from .subject import *
from .question import *
from .profiling import *
from .exam import *
from .answer import *
from .image import *